# Generated by Django 5.1.5 on 2026-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_production_execution',
            field=models.BooleanField(default=False, verbose_name='دسترسی به ثبت عملکرد/کارکرد شیفت (سرپرست واحد)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_planning',
            field=models.BooleanField(default=False, verbose_name='دسترسی به برنامه\u200cریزی تولید'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_production',
            field=models.BooleanField(default=False, verbose_name='دسترسی به کلیه بخش\u200cهای تولید'),
        ),
    ]
