# Generated by Django 5.1.5 on 2026-07-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_access_production_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_production_bom',
            field=models.BooleanField(default=False, verbose_name='دسترسی به ساختار درخت محصول (BOM) و MRP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_machines',
            field=models.BooleanField(default=False, verbose_name='دسترسی به ماشین\u200cآلات و تجهیزات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_maintenance',
            field=models.BooleanField(default=False, verbose_name='دسترسی به تعمیر و نگهداری (نت)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_operators',
            field=models.BooleanField(default=False, verbose_name='دسترسی به اپراتورها و پرسنل تولید'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_qc',
            field=models.BooleanField(default=False, verbose_name='دسترسی به کنترل کیفیت (QC)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_production_stages',
            field=models.BooleanField(default=False, verbose_name='دسترسی به مراحل کاری و خطوط تولید'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_production',
            field=models.BooleanField(default=False, verbose_name='مدیریت ارشد تولید (دسترسی کامل به کل بخش تولید)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='access_warehouse',
            field=models.BooleanField(default=False, verbose_name='دسترسی به انبار و موجودی'),
        ),
    ]
