# Generated by Django 5.1.5 on 2026-07-25 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_length_remove_orderitem_width_and_more'),
        ('production', '0003_maintenanceactivity'),
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_code', models.CharField(max_length=50, unique=True, verbose_name='کد ساختار BOM')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فرمول / ساختار درخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='نسخه فعال / اصلی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات و ملاحظات فنی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product', verbose_name='محصول اصلی (پایه)')),
            ],
            options={
                'verbose_name': 'ساختار درخت محصول (BOM)',
                'verbose_name_plural': 'ساختار درخت محصولات (BOM)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار مصرف استاندارد (به ازای ۱ واحد محصول)')),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد ضایعات / پرتی (%)')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات قطعه')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.bom', verbose_name='ساختار درخت BOM')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_usages', to='products.product', verbose_name='ماده اولیه / قطعه')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.workstage', verbose_name='مرحله مصرف کاری')),
            ],
            options={
                'verbose_name': 'قلم BOM',
                'verbose_name_plural': 'اقلام BOM',
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_code', models.CharField(max_length=50, unique=True, verbose_name='شماره برگه QC')),
                ('inspection_type', models.CharField(choices=[('incoming', 'ورودی مواد اولیه (IQC)'), ('in_process', 'حین تولید (PQC)'), ('finished', 'محصول نهایی (FQC)')], default='in_process', max_length=20, verbose_name='نوع بازرسی')),
                ('inspection_date', models.DateField(verbose_name='تاریخ بازرسی')),
                ('inspected_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='کل مقدار بازرسی شده')),
                ('passed_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار سالم / تایید شده')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار ضایعات / مردودی')),
                ('rework_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار نیازمند دوباره\u200cکاری')),
                ('defect_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع عیب / علت عدم تایید')),
                ('status', models.CharField(choices=[('passed', 'تایید شده (سالم)'), ('conditional', 'تایید مشروط'), ('rejected', 'مردود / ضایعات')], default='passed', max_length=20, verbose_name='نتیجه بازرسی')),
                ('action_taken', models.CharField(choices=[('accept', 'ورود به انبار اصلی'), ('rework', 'ارجاع به دوباره\u200cکاری'), ('scrap', 'انتقال به انبار ضایعات'), ('return', 'مرجوع به تامین\u200cکننده')], default='accept', max_length=20, verbose_name='اقدام انجام شده')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات فنی بازرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بازرس کیفیت')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='سفارش مرتبط')),
                ('planning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.planning', verbose_name='برنامه\u200cریزی تولید مرتبط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='کالا / محصول بازرسی شده')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='انبار مربوطه')),
            ],
            options={
                'verbose_name': 'برگه کنترل کیفیت (QC)',
                'verbose_name_plural': 'برگه\u200cهای کنترل کیفیت (QC)',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
    ]
