# Generated by Django 5.1.5 on 2026-07-25 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_bom_bomitem_qualitycontrol'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_code', models.CharField(max_length=50, unique=True, verbose_name='کد برگه ثبت عملکرد')),
                ('date', models.DateField(verbose_name='تاریخ تولید / ثبت کارکرد')),
                ('shift', models.CharField(choices=[('shift_1', 'شیفت اول (روز)'), ('shift_2', 'شیفت دوم (عصر)'), ('shift_3', 'شیفت سوم (شب)'), ('general', 'شیفت عمومی / روزانه')], default='shift_1', max_length=20, verbose_name='شیفت کاری')),
                ('produced_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار تولید واقعی (سالم)')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار ضایعات / پرتی')),
                ('stoppage_minutes', models.PositiveIntegerField(default=0, verbose_name='زمان توقف خط (دقیقه)')),
                ('stoppage_reason', models.TextField(blank=True, null=True, verbose_name='علت توقف خط / توضیحات مشکلات')),
                ('receive_to_warehouse', models.BooleanField(default=True, verbose_name='ارسال و رسید خودکار به انبار')),
                ('warehouse_received', models.BooleanField(default=False, verbose_name='آیا تحویل انبار ثبت شد؟')),
                ('deduct_raw_material', models.BooleanField(default=True, verbose_name='کسر خودکار مواد اولیه از انبار')),
                ('raw_material_deducted', models.BooleanField(default=False, verbose_name='آیا مواد کسر شد؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات سرپرست واحد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.operator', verbose_name='اپراتور مسئول')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='production.planning', verbose_name='برنامه\u200cریزی تولید مرتبط')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سرپرست ثبت\u200cکننده')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='انبار تحویل\u200cگیرنده محصول')),
            ],
            options={
                'verbose_name': 'گزارش عملکرد تولید (سرپرست واحد)',
                'verbose_name_plural': 'گزارش\u200cهای عملکرد تولید (سرپرستان واحدها)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
