# Generated by Django 5.1.5 on 2026-07-25 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_sepidar_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_drawings/%Y/%m/', verbose_name='فایل نقشه / طراحی')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان / توضیحات نقشه')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='orders.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'نقشه واحد طراحی',
                'verbose_name_plural': 'نقشه\u200cهای واحد طراحی',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
