# Generated by Django 5.1.5 on 2026-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdesignfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='length',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='width',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدل'),
        ),
    ]
