# Generated by Django 5.1.5 on 2026-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_length_remove_orderitem_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارسال سفارش'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سفارش\u200cگذاری'),
        ),
    ]
